[project]
name = "revenge"
version = "0.1.0"
description = "Thank you, big companies."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "cryptography>=44.0.0",
    "fastapi>=0.115.8",
    "uvicorn>=0.34.0",
]
